TOOL:
  FILTERING:
  # Parameters related with the power consupmtion filtering 
  # REQUIRED
    ENABLED: False # True or False
    ORDER: 16      # Integer
    FS: 500000    # Integer (Hz)
    CUTOFF: 50000 # Integer (Hz)
  OPTIONAL_PARAMETERS: 
  # Optional parameters
  # Would be requested by the tool if empty
    DUAL_MONITOR_ENABLED: True   # True, False or empty
    AXI_BUS_ENABLED: False        # True, False or empty
    SAMPLING_FREQUENCY_MHZ: 100   # Integer or empty (in MHz)
    NUMBER_SIGNALS : 16            # Integer or empty
    NUMBER_AXI_EVENTS : 0          # Integer or empty

MEASUREMENT_BOARD:
  # Required parameters
  ADC_REFERENCE_VOLTAGE: 2.5  # Float: 2.5 or 5.0 (vref of the adc)
  ADC_GAIN: 100               # Float 
  ADC_RESOLUTION: 12          # Integer (ADC resolution bits)
  SHUNT_RESISTOR: 5           # Integer (in mohm)
  SHUNT_RESISTOR_2: 2           # Integer (in mohm)
  VDD: 0.85                      # Float (supply voltage of the measured power rail)

# TODO: Add axi_address_with for automatic .BIN parsing
